const data = {
    products: [
      {
        name: 'Hand Bag',
        slug: 'Hand Bag',
        category: 'Designer Bag',
        image: '/images/p1.jpg', // 679px × 829px
        price: 120,
        countInStock: 10,
        brand: 'aura',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality shirt',
      },
      {
        name: 'Coir Basket',
        slug: 'Coir Basket',
        category: 'Shirts',
        image: '/images/p2.jpg',
        price: 250,
        countInStock: 20,
        brand: 'Aura',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        name: 'Hand Made Paper Craft',
        slug: 'Craft',
        category: 'Decors',
        image: '/images/p3.jpg',
        price: 25,
        countInStock: 15,
        brand: 'Aura',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        name: 'Gift Cards',
        slug: 'Gift Cards',
        category: 'Cards',
        image: '/images/p4.jpg',
        price: 65,
        countInStock: 5,
        brand: 'Aura',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
    ],
  };
  export default data;